#!/bin/sh

mkdir -p opk
cp ./fallingtime opk/fallingtime
cp ./data/icon_save.png opk/icon.png
cp -r data opk/
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Falling Time
Comment=Fall Down-like game
Exec=fallingtime
Icon=icon
Terminal=false
Type=Application
Categories=games;
' > opk/default."$1".desktop

mksquashfs ./opk fallingtime_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
